### ISSUE TITLE
Where is .cls file?

### ISSUE THREAD

**Issue by HarryXD2018** [note286/xduts#1]
I tried git clone the repo and ran the command, then I ran into bug report:
~~~
Qt: Untested Windows version 6.2 detected!
This is XeTeX, Version 3.1415926-2.3-0.9997.5 (MiKTeX 2.9)
entering extended mode
(...\xduts\xduts.ins
! I can't find file `ctxdocstrip'.
l.1 \input ctxdocstrip
~~~
Hmm, looks like .cls file is already added to .gitignore, should it be provided?

**Comment by note286** [comment]
[ctex-kit/ctxdocstrip.tex at master · CTeX-org/ctex-kit](https://github.com/CTeX-org/ctex-kit/blob/master/support/ctxdocstrip.tex)

**Comment by note286** [comment]
Don't use [CTEX](http://www.ctex.org/HomePage)!
