### ISSUE TITLE
biblatex如何使用，添加的bib库，但是并没有在参考文献中出现，有没有实例代码参考一下

### ISSUE THREAD

**Issue by Zhuzy0608** [note286/xduts#116]

**Comment by note286** [comment]
无需示例，阅读xduts手册即可。

**Comment by zjh2023** [comment]
> 无需示例，阅读xduts手册即可。

手册写得太简单了，东西太少，有很多可能并不精通latex知识，因此大多都是抱着学习态度

**Comment by note286** [comment]
@zjh2023 手册里已经说了，不会LaTeX的去看《一份（不太）简短的LATEX2ε介绍》(https://ctan.org/pkg/lshort-zh-cn)呀。这是LaTeX包，不是LaTeX教程。你总不能指望一个Python的库的手册里教你怎么使用Python吧。
