### ISSUE TITLE
关于a4页面大小的问题

### ISSUE THREAD

**Issue by Lincest** [note286/xduts#13]
## 问题

使用如下代码生成最小示例中, 可以看到实际生成的pdf纸张大小为`21.587cm x 27.937cm`:
```latex
\documentclass{xduugthesis}
\xdusetup{}
\begin{document}
\frontmatter
\mainmatter
\chapter{欢迎}
使用\LaTeX{}！
\backmatter
\end{document}
```
![image](https://user-images.githubusercontent.com/43769667/167811655-76208c8a-f264-46b7-b0bd-c1db058fe774.png)

![image](https://user-images.githubusercontent.com/43769667/167812057-0acab148-2056-443d-a2e7-5baa32930761.png)

然而实际的a4纸张大小应该为`21 cm x 29.7 cm`

## 尝试

修改代码为

```latex
\documentclass{xduugthesis}
\usepackage{geometry}
\geometry{a4paper}
\xdusetup{}
\begin{document}
\frontmatter
\mainmatter
\chapter{欢迎}
使用\LaTeX{}！
\backmatter
\end{document}
```

即在正文中显式指定`\geometry{a4paper}`后: 

```latex
\usepackage{geometry}
\geometry{a4paper}
```

生成的pdf大小恢复正常, acrobat显示为`20.998cm x 29.697cm`

![image](https://user-images.githubusercontent.com/43769667/167812683-8165d64e-e87c-432d-8fd9-81ac57af3a19.png)

我看到`xduts.pdf`中有对页面的定义

![image](https://user-images.githubusercontent.com/43769667/167813131-6c289056-7545-4367-80fc-bdc53681cfb4.png)

但是还是会出现这个问题, 我对latex也不是很了解, 不知道问题所在, 在此反馈下

**Comment by note286** [comment]
请使用最新版。

**Comment by Lincest** [comment]
问题解决, 我的锅, 感谢作者

> 请使用最新版。

**Comment by HarryXD2018** [comment]
为什么我git pull更新完之后还是没有变化呢，21.59*27.94

**Comment by HarryXD2018** [comment]
> 为什么我git pull更新完之后还是没有变化呢，21.59*27.94

OK 我的问题，我是在console里面安装的
