### ISSUE TITLE
导师名字含有生僻字，无法显示

### ISSUE THREAD

**Issue by winterant** [note286/xduts#134]
maxOS
导师中文姓名含有生僻字，无法显示
<img width="28" alt="image" src="https://github.com/note286/xduts/assets/37205944/1d988ae1-ffdf-4f1b-9442-0469afb6dc68">
尝试使用其它字体，无法编译
<img width="426" alt="image" src="https://github.com/note286/xduts/assets/37205944/8657cbe6-e870-4b0d-ac1b-34913239280a">
求指教～

**Comment by note286** [comment]
https://github.com/note286/xduts/discussions/88
