### ISSUE TITLE
请教：首页多个导师的情况下位置过于偏下怎么办？

### ISSUE THREAD

**Issue by winterant** [note286/xduts#136]
<img width="526" alt="image" src="https://github.com/note286/xduts/assets/37205944/2116976c-74bc-4809-aca5-98487796b2af">

**Comment by note286** [comment]
https://github.com/note286/xduts/blob/3237abfaf40e7c94a8e2b200bd4f5b2cb9b2c8bf/xduts.dtx#L7383

你可以修改这里的数值。

**Comment by winterant** [comment]
感谢感谢大佬🙏
我试试
