### ISSUE TITLE
缩略语对照表为空

### ISSUE THREAD

**Issue by lbz007** [note286/xduts#147]
我无论如何设置style/customize-los选项，缩略语页面都不能正确显示任何一条缩略语。而相对应的符号对照表却可以正确展示。我删除了所有中间文件并重新编译多次，依然没有解决。
一些相关设置如下
```
info / loa   = {chapters/loa.tex},
style / customize-loa = true,
```
我的loa.tex文件内容如下：
```
\begin{tabular}{lll}
缩略语 & 英文全称 & 中文对照 \\
BS 	& Binary Search & 二分查找	 \\
\end{tabular}
```

**Comment by lbz007** [comment]
非常抱歉。我发现这完全是我自己的问题。我使用了错误的编码格式在loa文件。现在一起正常了。
再次为我的粗心表示歉意。

**Comment by note286** [comment]
没关系，问题解决了就好。
