### ISSUE TITLE
博士论文怎么将英文页面的Dissertation修改为Thesis？

### ISSUE THREAD

**Issue by Han0nly** [note286/xduts#151]
您好，想问下博士论文怎么将英文页面的Dissertation修改为Thesis？

**Comment by note286** [comment]
这是学位办规定。

**Comment by Han0nly** [comment]
我看2022年11月发布的模版里面博士论文的英文这里还是thesis，这里可以修改吗？

**Comment by note286** [comment]
请你查看文件《3-4.西安电子科技大学英文学位论文撰写相关规定.doc》

> 页眉的“西安电子科技大学博士/硕士学位论文”统一翻译成：Doctoral Dissertation of XIDIAN UNIVERSITY/Master Thesis of XIDIAN UNIVERSITY。

**Comment by Han0nly** [comment]
好的收到，谢谢
