### ISSUE TITLE
表格宽度太宽放不下咋整？

### ISSUE THREAD

**Issue by JiaxiangHuang** [note286/xduts#152]
如题。求方法。
另外，算法名称如何分开放成两行呢

**Comment by note286** [comment]
请给出具体示例代码。

**Comment by JiaxiangHuang** [comment]
已解决：makecell
参考 https://blog.csdn.net/qq_41857385/article/details/129104359

**Comment by JiaxiangHuang** [comment]
这个issue 可以删除，谢谢
