### ISSUE TITLE
毕业设计论文题目过长，超出边界

### ISSUE THREAD

**Issue by wanstarge** [note286/xduts#153]
使用本科生毕业设计论文模板时，由于论文题目过长导致超出页面范围，不知道怎么产生新行，求助

**Comment by note286** [comment]
```latex
测试\\测试
```

**Comment by wanstarge** [comment]
哇，谢谢学长，突然就脑子卡壳了，还是用的不太熟，哈哈哈；那个封面字体的班级，学号有宋体选项吗，我看我们学院的模板要求用宋体小四，我转换了一下latex编译的PDF是思源宋体，我在字体选项中没有找到，还是默认就是宋体，是要修改这个地方吗：
```tex
\cs_new:Npn \__xdu_cover_i:nn #1#2
  {
    \vbox_to_ht:nn { 12pt }
      {
        \mode_leave_vertical:
        \hfill
        \hbox:n
          {
            \__xdu_rm_family: \zihao { -4 } \bfseries % TODO: 宋体
            \hbox_to_wd:nn { 3em } { #1 }
            \skip_horizontal:n { 1em }
            \__xdu_uline:n { \hbox_to_wd:nn { 15ex } { \hfil #2 \hfil } }
            \skip_horizontal:n { 1.5cm }
          }
      }
  }
```

还有就是文档中提到的“匿名”功能在本科毕设中无法使用，我看了一下dtx文件，好像标签只给pgthesis加了此选项

**Comment by wanstarge** [comment]
可以了，我才发现名字不一样，切换成学长提供的字体选项中的win模式就可以了，太感谢了，希望也能自己写一个这种模板，参与维护，哈哈哈，太感谢了

**Comment by note286** [comment]
> 还有就是文档中提到的“匿名”功能在本科毕设中无法使用，我看了一下dtx文件，好像标签只给pgthesis加了此选项

本科毕设应该是不需要盲审的。

**Comment by wanstarge** [comment]
> > 还有就是文档中提到的“匿名”功能在本科毕设中无法使用，我看了一下dtx文件，好像标签只给pgthesis加了此选项
> 
> 本科毕设应该是不需要盲审的。

需要吧，每年五月的时候书院会抽盲审，学校通知如下：
2024 年5 月6 日（星期一），学校通过教务系统随机抽取各学院盲审名单，并正式公布。
各学院组织学生提交符合要求的毕业设计（论文）材料（毕业设计（论文）需指导教师给出评阅
意见），于5 月9 日（星期四）前收齐并上报。本科生院组织专家实施盲审评审工作，并公布盲审评审结果

**Comment by note286** [comment]
时间长了有点记不清了，xduts已经经历了一届本科毕业，功能上是没啥问题的。

你可以再看一下5.21.2 相似性检测、盲审和抽查评估，仔细读一下，你就知道怎么应对盲审了。

**Comment by wanstarge** [comment]
谢谢学长，感谢，可能之前没有吧，哈哈哈，反正自从那次造假被曝光之后就变严了，而且直接把上一届毕业的人都整回来重新查了一遍论文😹，多谢

**Comment by note286** [comment]
xduts的所有个人信息都是通过接口录入的，如果需要盲审，直接注释掉对应行就行，非常方便，可以应对不同学院的不同要求。

**Comment by wanstarge** [comment]
嗯嗯嗯嗯，看dtx文件的时候发现了，结构化的代码太酷啦，学长辛苦🌹🌹🌹，已star，马上推给身边的人🧉

**Comment by wanstarge** [comment]
嗯嗯，只是好奇，想学习一下，看以后能帮忙维护不，嘿嘿，然后感觉很有意思，很厉害，学长在这上面下了很大苦心，后续赞助一杯奶茶🧋，哈哈

**Comment by note286** [comment]
不是很建议花时间在这上面，还是在学业上多花点时间吧，功利点讲没有任何益处。

**Comment by wanstarge** [comment]
嗯嗯，收到，记住了，我就先学会基本的使用吧，后面可能还要多请教学长您，最近甲流挺严重，喝点热的（应该没发错人吧😂），哈哈哈🌹🌹🌹
