### ISSUE TITLE
建议：现在好多中间文件（输出文件）和源文件都在一个文件夹中（大多数情况下输出文件只有 PDF 有用），VSCode 如何配置编译输出路径？

### ISSUE THREAD

**Issue by lutianen** [note286/xduts#156]
建议：现在好多中间文件（输出文件）和源文件都在一个文件夹中（大多数情况下输出文件只有 PDF 有用），VSCode 如何配置编译输出路径？

**Comment by lutianen** [comment]
建议：现在好多中多文件都在一个文件夹中（大多数情况下只有 PDF 有用），VSCode 如何配置编译输出路径？

settings.json 设置后，出现报错如下：

![image](https://github.com/note286/xduts/assets/61954994/9d977e21-88c2-4657-a90c-8e756344e7c4)

**Comment by note286** [comment]
我不使用VS Code，不过我猜测你应该建立VS Code项目，通过项目配置文件隐藏指定扩展名的文件。

此问题与LaTeX无关，故关闭，你可以去VS Code社区进行讨论。

**Comment by sikouhjw** [comment]
事实上可以使用 `--output-directory` 命令行选项实现[^1]。

[^1]: https://github.com/James-Yu/LaTeX-Workshop/issues/1603
