### ISSUE TITLE
overleaf上xdufont.sty编译错误

### ISSUE THREAD

**Issue by butaihuicode** [note286/xduts#162]
overleaf报如下错，不知如何解决
<img width="584" alt="截屏2024-02-25 11 28 47" src="https://github.com/note286/xduts/assets/91518739/a094aaee-2f10-493f-8afd-6fb86fb3bfee">

**Comment by note286** [comment]
请认真阅读手册，`xdufont.sty`、`xduugtp.cls`、`xduugthesis.cls`、`xdupgthesis.cls`是互相独立的，不要共用。

**Comment by butaihuicode** [comment]
感谢！已解决
