### ISSUE TITLE
[EB/OL]类型的参考文献不显示日期

### ISSUE THREAD

**Issue by devindang** [note286/xduts#173]
![image](https://github.com/note286/xduts/assets/39517801/ef3d2678-0dce-49ed-aae7-ebfeb81a307e)

```
@misc{fmax,
  title = {UltraFast Design Methodology Guide for FPGAs and SoCs (UG949)},
  author = {Xilinx},
  url = {https://docs.xilinx.com/r/en-US/ug949-vivado-design-methodology/Assessing-the-Maximum-Frequency-of-the-Design},
  date = {2023-11}
}
```

urldate 和 date 都不会显示。请问怎么解决

**Comment by devindang** [comment]
只在“类别代码”和“获取路径”中间显示了年份，和学校给的这个不太一样。
![image](https://github.com/note286/xduts/assets/39517801/71c82a55-9206-48cc-a96a-0cb58ba26286)

**Comment by note286** [comment]
建议参考GB/T 7714-2015中的示例。

**Comment by devindang** [comment]
> 建议参考GB/T 7714-2015中的示例。

学校的好像是GB/T 7714-2005。但是为啥编译出来和2015的也不太一样嘞 : (

**Comment by note286** [comment]
请阅读`biblatex-gb7714-2015`手册4.3.8 电子资源/online：

> 注意修改日期需要表示到日。

**Comment by devindang** [comment]
> > 学校的好像是GB/T 7714-2005。
> 
> 你使用GB/T 7714-2015即可，不必过于考究学位办给出的示例细节。

谢谢！
