### ISSUE TITLE
使用parencite引用，编译出来的引用标号后有一个空格

### ISSUE THREAD

**Issue by devindang** [note286/xduts#176]
![image](https://github.com/note286/xduts/assets/39517801/08134e35-f0ce-4851-a293-cccb7fc00d85)
我看了 #62 里面的问题，并没有加载任何和参考文献相关的宏包。

请问这个是正常的吗？我看了文档，并没有找到相关的描述。

这是我用到的所有的宏包：
![image](https://github.com/note286/xduts/assets/39517801/8c257a2c-8968-4d1c-933b-e1f92ef53a0e)

**Comment by note286** [comment]
请给出能复现问题的完整代码，尽量不要让我猜测。完整不意味着全部代码，目的是直接能复现问题。

**Comment by devindang** [comment]
> 请给出能复现问题的完整代码，尽量不要让我猜测。完整不意味着全部代码，目的是直接能复现问题。

这是可以复现问题的完整代码

```
% main.tex
\documentclass{xdupgthesis}
\xdusetup{
    style   /   cjk-font            = win,
    style   /   latin-font          = tac,
    style   /   table-small-font    = true,
    style   /   bib-backend         = biblatex,
    info    /   bib-resource        = {ref.bib}
}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{docmute}

\begin{document}

	文献\parencite{koren2018computer}提到

\end{document}
```

```
% ref.bib
@book{koren2018computer,
  title={Computer arithmetic algorithms},
  author={Koren, Israel},
  year={2018},
  publisher={CRC Press}
}
```

![image](https://github.com/note286/xduts/assets/39517801/ecaedcb2-c00e-4651-a0f1-90bd8efb1d0f)

**Comment by note286** [comment]
你应该写作`文献 \parencite{koren2018computer}提到`或者`文献 \parencite{koren2018computer} 提到`。

你可以尝试`文献[1]提到`的效果，你就明白是怎么回事了。
