### ISSUE TITLE
图片标题中的脚注和引用

### ISSUE THREAD

**Issue by 1518064060** [note286/xduts#178]
![image](https://github.com/note286/xduts/assets/63624076/da033109-1700-45b7-8a1c-60e461ba7a16)
![image](https://github.com/note286/xduts/assets/63624076/a9222e78-09ee-49ca-b39d-0c1a7d9e36d1)
例如想要给图片名称加上引用或脚注，文本中可以显示，但是在图片索引中无法显示图片名称，有大佬知道如何解决嘛！！！

**Comment by note286** [comment]
下次建议使用文本提供代码，而不是图片。

```latex
\documentclass{xdupgthesis}
\usepackage{graphicx}
\begin{document}
\begin{figure}
\includegraphics[width=\linewidth]{example-image}
\caption[title]{title\footnotemark}
\label{key}
\end{figure}
\footnotetext{text}
\end{document}
```

**Comment by 1518064060** [comment]
感谢大佬
