### ISSUE TITLE
参考文献配置

### ISSUE THREAD

**Issue by xlli-2** [note286/xduts#20]
- TeX 3.141592653 (TeX Live 2022)
- 配置了info/bib-resource ，但是参考文献没有出现
- 使用的版本是[v4.0.1.1](https://github.com/note286/xduts/releases/tag/v4.0.1.1)
- 
![image](https://user-images.githubusercontent.com/52368227/207520413-8d76cdb1-8bb5-439f-b0fc-134d4633d575.png)

**Comment by note286** [comment]
你需要使用`\cite`引用啊，不引用怎么出现，这是LaTeX常识。

**Comment by xlli-2** [comment]
![image](https://user-images.githubusercontent.com/52368227/207520998-a4eeffa3-04da-49e0-b234-489f77b7268c.png)![image](https://user-images.githubusercontent.com/52368227/207520849-bd6093d7-5d03-4ca5-a242-3f0babaf1e8b.png)
![image](https://user-images.githubusercontent.com/52368227/207520925-658c7274-0c5f-4dff-85da-be23adcea895.png)

使用`\cite` 引用了

**Comment by note286** [comment]
需要`xelatex-biber-xelatex`编译才可以啊。

**Comment by note286** [comment]
@xlli-2 如果不确定是bug，请在讨论区交流，这一点在手册里写的很清楚。另外，你甚至没有star，:sob:。
