### ISSUE TITLE
关于使用\documentclass{xdupgthesis}的时间相关的问题

### ISSUE THREAD

**Issue by TIAN-CUTE** [note286/xduts#202]
首先祝 Dr. 今天端午节快乐，新手初探latex，使用 \documentclass{xdupgthesis} 撰写硕士论文，设置论文提交日期时
采用
代码1：submit-date = ⟨2025-4⟩,
代码2：submit-date = ⟨2025-04⟩,
生成的pdf文件，英文页面，都只出现2025，并没有出现 April 2025。
想知道是哪里弄错了，求作者大大指点

**Comment by note286** [comment]
https://github.com/note286/xduts/discussions/169

**Comment by TIAN-CUTE** [comment]
你好，您的邮件已收到，我将尽快阅读，谢谢。
