### ISSUE TITLE
  英文论文：按照xduts.pdf（中英文标题显示）在正文中显示中文

### ISSUE THREAD

**Issue by Saiqin** [note286/xduts#204]
![image](https://github.com/user-attachments/assets/716839f1-b07b-4483-bdeb-f2027198634a)
![image](https://github.com/user-attachments/assets/edd55ccf-0916-4b68-a44c-52b4f1fce3ab)
你好 我按照 说明文档，还是在正文中出现中文标题呢？非常感谢

**Comment by note286** [comment]
```latex
\chapter{title}[标题]
```

**Comment by Saiqin** [comment]
感谢！
