### ISSUE TITLE
每个章节后均增加一个空白页

### ISSUE THREAD

**Issue by lzu-zhanghr** [note286/xduts#34]
- 无法在 cls 文件中设置 openan y解决上述问题
- 在 cls 中设置 oneside 可以解决空白页问题， 但与现有页面布局不兼容，引起 warning

**Comment by note286** [comment]
我没有理解你的描述。

论文是要装订的，每一章首页必须在奇数页。

**Comment by lzu-zhanghr** [comment]
🙄是我浅薄了，没有理解论文的要求



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月20日 18:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [note286/xduts] 每个章节后均增加一个空白页 (Issue #34) |

我没有理解你的描述。

论文是要装订的，每一章首页必须在奇数页。
