### ISSUE TITLE
Runaway argument? ! Paragraph ended before  \chapter  was complete.

### ISSUE THREAD

**Issue by wail-asad** [note286/xduts#35]
### **Platform** : windows 11
###  **Latex** : Texlive 2022 
This  appeared  at the following configurations
-----------------------------------------------------
- `style / language = en,`
- `\chapter{Introduction}`
- There is empty line in code for example
```
\chapter{Introduction}

   This the first part
```
- it will disappear if there is no line for example
```
\chapter{Introduction}
This the first part
```
or if there is chinese title 
```
\chapter{Introduction}{Chinese title}

This the first part
```
or if the language is chinese  for example
`style / language = zh,`

**Comment by wail-asad** [comment]
@note286 could you please look for it.

**Comment by note286** [comment]
Are you going to write an English thesis? Or Chinese? I don't quite understand your problem. What do you think is wrong.

**Comment by note286** [comment]
According to the regulations of the university, the English thesis must have a bilingual directory. The directory level is 3.

```latex
\documentclass{xdupgthesis}
\xdusetup{style/language=en}
\begin{document}
\chapter{This Is Chapter}{这是一级标题}
This the text.
\section{This Is Section}{这是二级标题}
This the text.
\subsection{This Is Subsection}{这是三级标题}
This the text.
\subsubsection{This Is Subsubsection}
This the text.
\paragraph{This Is Paragraph}
This the text.
\subparagraph{This Is Subparagraph}
This the text.
\end{document}
```
![image](https://user-images.githubusercontent.com/16207292/215243159-271d62bf-01e9-4d52-9360-dfec46a62692.png)
![image](https://user-images.githubusercontent.com/16207292/215243164-a0c2458c-eb20-485d-89d1-4ffb34c8bfcc.png)
![image](https://user-images.githubusercontent.com/16207292/215243168-bf657b35-76d2-4c7d-9531-49bf6f030435.png)

**Comment by wail-asad** [comment]
Ok, noted thanks very much
