### ISSUE TITLE
字体问题

### ISSUE THREAD

**Issue by zxin8218** [note286/xduts#39]
您好！ 感谢开源，用您这个模板还需要修改字体吗，我写摘要的时候发现标点符号`,` 、括号等和word模板里面的不一样，配置是下面这样！
我以为是字体的原因，修改`style / cjk-font = sinotype` 会报错，是怎么回事呢？
```
\documentclass[mprof]{xdupgthesis}
\xdusetup{
	style / cjk-font = sinotype,
	style / latin-font = gyre,
	info / abstract = {chapters/abstract-zh.tex},
	info / keywords = {Dummy,Keywords,Here,it is},
	info / abstract* = {chapters/abstract-en.tex},
}
\begin{document}
	\include{chapters/first}
	\include{chapters/second}
	
\end{document}
```

**Comment by note286** [comment]
`[mprof]`是什么?

**Comment by note286** [comment]
确保你已经安装了相应的字体文件.

![image](https://user-images.githubusercontent.com/16207292/217798869-48328f68-1032-43f6-b2ba-c13edec18e70.png)

**Comment by zxin8218** [comment]
> `\xdusetup{style/cjk-font=win}`

感谢大佬及时回复，问题解决了！还有个问题，字体这块只需要设置成下面这样就可以了嘛，不知道哪里还需要注意修改的，可以的话您指教下
```
\xdusetup{
	style / cjk-font = win,
	style / latin-font = gyre,
	info / abstract = {chapters/abstract-zh.tex},
	info / keywords = {Dummy,Keywords,Here,it is},
	info / abstract* = {chapters/abstract-en.tex},
}
```

**Comment by note286** [comment]
学校对字体的要求不限制厂商，所以，文档里提及的中文字体配置均可。

至于英文字体，`gyre`系列为开源的Times风格字体，一般人看不出和Times New Roman的差异，使用也没关系。

简单来说，不要细抠Microsoft Word模板的细节，很多都经不起推敲。

**Comment by note286** [comment]
数学字体学校没有要求，我推荐使用`xits`，这是Times风格的数学字体。

与正文比较搭配，与Computer Modern字体常见的使用区别有加粗的用法，需要使用`\symbfit{\alpha}`加粗。

你可以在正文中对比字体差异，例如`\textit{x} $x$`。

**Comment by zxin8218** [comment]
> 

哈哈哈 专业啊 感谢感谢
