### ISSUE TITLE
不同页缩略语对照表内容没有对齐

### ISSUE THREAD

**Issue by XDUXTU** [note286/xduts#44]
当设置为
`style/customize-loa = false, style/colspec-loa = {X[1]X[3.5]X[1.7]},`
奇数页和偶数页的对照表内容对不齐 偶数页和偶数页 奇数页和奇数页 是对齐的
<img width="346" alt="issue" src="https://user-images.githubusercontent.com/125463275/219023768-897ddd22-89a8-40e6-9c8a-df81af204d80.png">

**Comment by note286** [comment]
有没有一种可能，奇偶页左右页边距不同。

**Comment by XDUXTU** [comment]
> 有没有一种可能，奇偶页左右页边距不同。

emmmm，是我的问题
