### ISSUE TITLE
正文中使用英文括号出现问题

### ISSUE THREAD

**Issue by XDUXTU** [note286/xduts#46]
请问
<img width="283" alt="issue" src="https://user-images.githubusercontent.com/125463275/219251975-e5d8e1ba-22f3-4718-8f54-f822ce48dfca.png">
正文中使用英文括号时，会出现英文括号下边沿与汉字下边沿不对齐的情况，打印出来不美观，能够解决吗
字体设置为如下
`style = {cjk-font = founder, latin-font = gyre}`

**Comment by note286** [comment]
Microsoft Word也是如此啊。

![image](https://user-images.githubusercontent.com/16207292/219254206-12ec782e-78fa-4e18-8831-ea197038ba38.png)

这样你就不觉得有问题了，这是因为你示例中的单词都是在基线之上的。

![image](https://user-images.githubusercontent.com/16207292/219254303-d960dea1-5e90-4815-97b9-5a918efd265c.png)

以上示例均为Microsoft Word输出。

**Comment by XDUXTU** [comment]
> 

懂了懂了，非常感谢
