### ISSUE TITLE
页码及正文字体，以及中文摘要中英文关键词问题

### ISSUE THREAD

**Issue by IskandarZhang** [note286/xduts#6]
作者你好，
页码现有字体目测是times new roman，手册中要求宋体。
正文字体不知道是否满足14pt 宋体？
中文摘要中关键词如果出现英文，则显示为黑体 根据手册是否应为times new roman？
希望能给出修改指导 谢谢

**Comment by note286** [comment]
请认真阅读手册，查看`en-cjk-font`选项介绍后，如果仍有疑惑，再提问。

**Comment by note286** [comment]
> 每篇论文选取3-5个关键词，中文为黑体小四号，英文为“Times New Roman”字体加粗，小四号。

我对此的解释是，中文摘要对应的关键词全部为黑体，英文摘要对应的关键词全部为Times New Roman。理由如下，Times New Roman为罗马字体族，黑体为无衬线字体族是约定俗成的，因此，中文摘要对应的关键词出现英文，应保持相同字体族。

**Comment by note286** [comment]
你为何对正文字号会产生质疑？另外，小四为12bp，和14pt并不等价。不知你哪里看到的14pt。

**Comment by IskandarZhang** [comment]
> > 每篇论文选取3-5个关键词，中文为黑体小四号，英文为“Times New Roman”字体加粗，小四号。
> 
> 我对此的解释是，中文摘要对应的关键词全部为黑体，英文摘要对应的关键词全部为Times New Roman。理由如下，Times New Roman为罗马字体族，黑体为无衬线字体族是约定俗成的，因此，中文摘要对应的关键词出现英文，应保持相同字体族。

受教了，我再去查阅手册，感谢回复
