### ISSUE TITLE
13build doc  问题

### ISSUE THREAD

**Issue by zilangch** [note286/xduts#67]
![image](https://user-images.githubusercontent.com/28552847/224524682-943f57e6-1e36-4cb1-b993-929747e1e824.png)

**Comment by note286** [comment]
根据readme提示更新所有包。

**Comment by zilangch** [comment]
![image](https://user-images.githubusercontent.com/28552847/224526423-1334936a-e7cd-4df2-995e-e261df09a694.png)

这是只能重新去安装 2022版本了吗？

**Comment by zilangch** [comment]
解决了，换个版本

**Comment by note286** [comment]
- 给个star呀，/(ㄒoㄒ)/~~
- 可以跨版本更新，可以参考 [https://rs.xidian.edu.cn/forum.php?mod=viewthread&tid=1142183](https://rs.xidian.edu.cn/forum.php?mod=viewthread&tid=1142183) 或者 [https://syvshc.github.io/2022-04-04-texlive-rolling-update/](https://syvshc.github.io/2022-04-04-texlive-rolling-update/)。
- 或者可以参考README中的Overleaf的使用方法，直接获取文档类文件和文档，不过还是更推荐更新TeX Live。
