### ISSUE TITLE
Latex模板 封面如何修改问题

### ISSUE THREAD

**Issue by zilangch** [note286/xduts#68]
latex模板：
![image](https://user-images.githubusercontent.com/28552847/224540491-ab07996c-8a80-4f1c-bd9c-f92124a7398e.png)
![image](https://user-images.githubusercontent.com/28552847/224540496-b4dd4278-7df8-448e-8c77-c837dcc64787.png)

学校word模板(2015年修订版)
![image](https://user-images.githubusercontent.com/28552847/224540518-662705c2-5c4a-42fd-ad99-44f0bf8524a1.png)
![image](https://user-images.githubusercontent.com/28552847/224540536-3f777ff2-82de-40e5-9dda-9efce8b65e6f.png)

请问怎么修改和删除？（去.cls我看都有，是不是可以切换？）

**Comment by note286** [comment]
首先，你的问题描述不清楚，不要让我去琢磨，清楚地描述出你认为缺少什么或者多什么？

另外，请认真阅读文档，所有学位类型均可切换。

**Comment by sikouhjw** [comment]
这样那样，改完就可以了

**Comment by note286** [comment]
我猜测是他其实是专业硕士，但是他并不知道西安电子科技大学对于专业硕士有单独的封面，与学硕不同，每年都有问的。

**Comment by note286** [comment]
不过即使是专硕，我在手册中也提及了专硕对应的封面文件名称。看手册不仔细的话，起码要`Ctrl+F`啊。

**Comment by zilangch** [comment]
不好意思，我重新描述一下：

latex模板封面第一页显示的是 “学校导师姓名、职称”，学校word模板(2015年修订版) 则显示的是“指导教师姓名、职称”，以及并没有“企业导师姓名、职称”这一行；在第二个封面中latex模板显示有“领域”，“企业导师姓名、职称”，学校word模板(2015年修订版) 则没有这几行，并且有“一级学科”，“二级学科”这两行latex模板未显示。

问题：怎么修改封面，删除latex模板多的行，修改不一样的行

**Comment by note286** [comment]
你自己设置的`info/degree-type=专业`。

**Comment by zilangch** [comment]
原来如此，感恩！

**Comment by note286** [comment]
你到底是学硕还是专硕？你是不清楚专硕有单独的封面还是你误操作设置为了专硕？

**Comment by zilangch** [comment]
我是专硕

**Comment by note286** [comment]
问题是我在 https://github.com/note286/xduts/issues/68#issuecomment-1465163642 和 https://github.com/note286/xduts/issues/68#issuecomment-1465168084 都告诉你专硕有单独的封面了啊。

我倒现在都好奇到底以上的对话怎么发展到这个地步的。

**Comment by zilangch** [comment]
emmm，大概是 不清楚键对应的显示效果 和 对学硕专硕的封面 认识不够

**Comment by note286** [comment]
(⊙o⊙)… 算了，以后认真点，手册里已经专门提及了这一点。在你提问之后，我也回复了两条告诉你专硕有单独的封面，你还是当看不见。ε=(´ο｀*)))唉，认真点吧，都快毕业了。

**Comment by zilangch** [comment]
嗯嗯，非常感谢！
