### ISSUE TITLE
文章正文出现长单词不能自动换行

### ISSUE THREAD

**Issue by IskandarZhang** [note286/xduts#7]
作者你好，
我在正文中编辑长指令时遇到了这个问题，源代码如下
```
\section{TCL指令写法}
本文中通过编写流式内核连接参数实现了子系统间 Stream 类型模块的相互连接，具体Tcl指令遵从stream\_connect=<cu\_name>.<output\_port>:<cu\_name>.<input\_port>的格式。
......
```
编译结果显示为：
![QQ图片20220503123310](https://user-images.githubusercontent.com/57842153/166404963-4e24b53e-3f9d-42c9-8a39-3e0e2610e449.png)

可以看到图中第一行显示正常，第二行似乎将这串指令识别为了一个完整单词？

**Comment by note286** [comment]
可以了解一下`seqsplit`宏包。

**Comment by atxy-blip** [comment]
TeX 只会在特定的字母组合间断词。这个指令显然不符合传统的英文模式，简单处理就是在合适的位置手动加个 `\\` 换行，当然 `seqsplit` 包更好用。

此外，图中呈现的代码是不是*不像*代码？建议使用等宽字体（`\texttt{}`）来表示这种类似于行内代码的内容，以增强可读性。再进一步，要不要用抄录环境（`fancyvrb` 包）以避免对特殊字符手动转义、或者要不要用行内代码环境（`listings` 包）进行抄录并提供语法高亮，也都可以纳入考虑。

**Comment by note286** [comment]
@atxy-blip 大佬说的对，对于等宽字体我也想告诉 @IskandarZhang 了，不过根据我在[note286/xdupgthesis: 西安电子科技大学研究生学位论文XeLaTeX模板](https://github.com/note286/xdupgthesis)项目的经验，说的越多，用户越迷糊，既然用户提问，说明其不太具备独立解决问题或者解决复杂问题的能力，给出一个简单的解决办法是对双方都友好的做法。所以，我就给出了[CTAN: Package seqsplit](https://ctan.org/pkg/seqsplit?lang=en)这一效果很好，又很简单的办法:joy:。
