### ISSUE TITLE
pdf目录、更新的配置

### ISSUE THREAD

**Issue by zxin8218** [note286/xduts#71]
您好！ 我根目录是这样写的，最后生成的pdf标签只有一级标题，是写法不对嘛，试了网上的办法也不管用
```
\begin{document}
	\include{chapters/first}
	\include{chapters/second}
\end{document}
```

还有，像您修复的一些bug，我只需要替换原来的文件就可以了嘛？ 需要重新编译啥的不？  我就是直接替换，发现尾页还是作者简介（无空白页？）

**Comment by note286** [comment]
根据README中的安装流程重新走一遍不就好了？

**Comment by zxin8218** [comment]
> 根据README中的安装流程重新走一遍不就好了？

好的好的 谢谢啦

**Comment by note286** [comment]
我以为知道怎么安装就能联想到更新是一样的，看来我还是补充一下README吧，ε=(´ο｀*)))唉。

**Comment by zxin8218** [comment]
> 我以为知道怎么安装就能联想到更新是一样的，看来我还是补充一下README吧，ε=(´ο｀*)))唉。

没没没 我也想到了重新装一遍，原以为编译的时候会读你更新的配置，就随口问了下  嘻嘻  不好意思

**Comment by note286** [comment]
> 大佬 pdf标签那块有啥好的建议嘛

老早就修复了

**Comment by zxin8218** [comment]
> > 大佬 pdf标签那块有啥好的建议嘛
> 
> 老早就修复了
好的 谢啦

**Comment by note286** [comment]
README更新了，加了关于更新的说明。

**Comment by zxin8218** [comment]
> README更新了，加了关于更新的说明。

啊哈哈哈 怪我
