### ISSUE TITLE
关于 xduts 更新问题

### ISSUE THREAD

**Issue by Jamie-obj** [note286/xduts#86]
我使用readme给出的更新方法，下载仓库压缩包在本地编译安装:
```
xetex xduts.ins
l3build doc
```
更新后运行`texdoc xduts`命令，文档的版本号还是上次安装时的版本，请问我这个是更新成功了还是没更新成功呢？

![图片](https://user-images.githubusercontent.com/65389500/226575386-b529fd6a-7038-45ba-be35-c985cccb08f6.png)

**Comment by note286** [comment]
你弄混了，`texdoc xduts`是打开TeX Live里的。

**Comment by note286** [comment]
只需要放在`.tex`同一目录下即可。

**Comment by Jamie-obj** [comment]
> 你弄混了，`texdoc xduts`是打开TeX Live里的。

多谢解答
